import streamlit as str
str.subheader("spotify")
str.image("whatareboobs.jpg",caption="made with python and alex",width=500)
with str.sidebar:
    tame_impala = str.button("tame impala")
    tv_girl = str.button(" tv girl")
    mac_demarco = str.button("mac demarco")
    eye_dress = str.button("eye dress")
    others = str.button("others")
    mylink = str.link_button("my spotify link!",url="https://open.spotify.com/user/31tqnpgz6zm7ccb6esvah73bgehm?si=290c815c45b44835")
if tame_impala:
    str.markdown("___")
    str.markdown("*let it happen*")
    str.audio("letithappen.mp3")
    str.markdown("*the less i know the better*")
    str.audio("lessik.mp3")
    str.markdown("*borderline*")
    str.audio("borderline.mp3")
    str.markdown("*lost in yesterday*")
    str.audio("lostyesterday.mp3")
    str.markdown("*eventually*")
    str.audio("eventually.mp3")
    str.markdown("*neverender*")
    str.audio("neverender.mp3")
    str.markdown("*new person,same old mistakes*")
    str.audio("newperson.mp3")
if tv_girl:
    str.markdown("___")
    str.markdown("*not allowed*")
    str.audio("notallowed.mp3")
    str.markdown("*louise*")
    str.audio("louise.mp3")
    str.markdown("*lovers rock*")
    str.audio("loversrock.mp3")
    str.markdown("*taking what's not yours*")
    str.audio("taking.mp3")
if mac_demarco:
    str.markdown("___")
    str.markdown("*freaking out the neighborhood*")
    str.audio("freaking.mp3")
    str.markdown("*chamber of reflection*")
    str.audio("chamber.mp3")
    str.markdown("*heart to heart*")
    str.audio("h2h.mp3")
if eye_dress:
    str.markdown("___")
    str.markdown("*something about you*")
    str.audio("somethingabout.mp3")
    str.markdown("*jealous*")
    str.audio("jealous.mp3")
    str.markdown("*romantic lover*")
    str.audio("romantic.mp3")
if others:
    str.markdown("___")
    str.markdown("*af1*")
    str.audio("af1.mp3")
    str.markdown("*harvey_her's*")
    str.audio("harvey_her's.mp3")
    str.markdown("*island_song*")
    str.audio("island_song.mp3")
    str.markdown("*deceptacon_le_tigre*")
    str.audio("deceptacon.mp3")
    str.markdown("*chandelier*")
    str.audio("chandelier.mp3")
    str.markdown("*mrs_magic*")
    str.audio("mrs_magic.mp3")
    str.markdown("*dark_red*")
    str.audio("dark_red.mp3")
    str.markdown("*looking out for you*")
    str.audio("looking_out.mp3")
    str.markdown("*music sounds better with you*")
    str.audio("better_with_you.mp3")
    str.markdown("*casin*")
    str.audio("casin.mp3")
    str.markdown("*jigsaw falling into place*")
    str.audio("jigsaw.mp3")
    str.markdown("*crave you*")
    str.audio("craveyou.mp3")
    str.markdown("*fight!*")
    str.audio("fight.mp3")
    str.markdown("*walking on a dream*")
    str.audio("walking.mp3")

